version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - beautysyncpro-network

  frontend:
    build:
      context: .
      dockerfile: frontend/frontend.Dockerfile
    ports:
      - "80:80"
    networks:
      - beautysyncpro-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/1-init_db.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/2-seed_data.sql
    ports:
      - "3306:3306"
    networks:
      - beautysyncpro-network

volumes:
  db_data:

networks:
  beautysyncpro-network:
    driver: bridge