version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://root:aditya230f@db:3306/beautysyncpro
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aditya230f
      MYSQL_DATABASE: beautysyncpro
      MYSQL_USER: root
      MYSQL_PASSWORD: aditya230f
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
