services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - beautysyncpro-network

  db:
    image: mysql:8.0.42
    environment:
      - MYSQL_ROOT_PASSWORD=aditya230f
      - MYSQL_DATABASE=beautysyncpro
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pmysqlpass123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - beautysyncpro-network

networks:
  beautysyncpro-network:
    driver: bridge

volumes:
  db-data: